feat: add MicroplateSet
mll-lab/microplate pull request #24
Opened 2023-06-02 14:15 UTC by simbig

- [x] Added automated tests
- [x] Documented for all relevant versions
- [x] Updated the changelog

**Changes**

- Add `MicroplateSet` possibility to calculate a `Location` within this set by a position

2023-06-02 14:18 UTC, simbig commented on src/MicroplateSet/MicroplateSet.php
> +        );
@spawnia can you help me to fix this stan error:

```55     Method Mll\Microplate\MicroplateSet\MicroplateSet::locationFromPosition() should return Mll\Microplate\MicroplateSet\Location<TCoordinateSystem of Mll\Microplate\CoordinateSystem> but returns Mll\Microplate\MicroplateSet\Location<Mll\Microplate\CoordinateSystem>.```

2023-06-05 07:43 UTC, spawnia requested changes

2023-06-05 07:43 UTC, spawnia commented on src/MicroplateSet/Location.php
> +    public $coordinate;
```suggestion
    public Coordinate $coordinate;
```

2023-06-05 07:43 UTC, spawnia commented on src/MicroplateSet/Location.php
> +        $this->plateID = $plateId;
```suggestion
    public function __construct(Coordinate $coordinate, string $plateID)
    {
        $this->coordinate = $coordinate;
        $this->plateID = $plateID;
```

2023-06-05 07:43 UTC, spawnia commented on src/MicroplateSet/MicroplateSet.php
> +        );
Generic inference is too weak to recognize this code is correct, I would just ignore the error here.

2023-06-05 07:43 UTC, spawnia commented on src/MicroplateSet/MicroplateSetABCD.php
> +     */
```suggestion
```

2023-06-05 07:43 UTC, spawnia commented on tests/Unit/MicroplateSet/MicroplateSetTest.php
> +                ], [
```suggestion
        yield [
            'position' => 1,
            'coordinateString' => 'A1',
            'plateID' => 'A',
        ];
        yield [
            'position' => 2,
            'coordinateString' => 'B1',
            'plateID' => 'A',
        ];
```

And so on. Reduces indentation by 8. Same in the other data provider.

2023-06-05 07:43 UTC, spawnia commented on tests/Unit/MicroplateSet/MicroplateSetTest.php
> +    public static function dataProvider96Well(): array
```suggestion
     * @return iterable<array{position: int, coordinateString: string, plateID: string}>
     */
    public static function dataProvider96Well(): iterable
```

2023-06-06 12:00 UTC, spawnia approved these changes

2023-06-07 06:05 UTC, merged